apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: html-rollout
spec:
  replicas: 4
  selector:
    matchLabels:
      app: html-app
  template:
    metadata:
      labels:
        app: html-app
      annotations:
        rollouts.argoproj.io/version: "v1"
    spec:
      containers:
        - name: nginx
          image: nginx:1.17.0
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html
      volumes:
        - name: html
          configMap:
            name: html-page
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: { duration: 20s }
        - setWeight: 50
        - pause: { duration: 20s }
        - setWeight: 100
